return {
  CinderGroveBg = { fg = 'bg' },
  CinderGroveBgAlt = { fg = 'bg_alt' },
  CinderGroveSurface = { fg = 'surface' },
  CinderGroveMuted = { fg = 'muted' },
  CinderGroveGray = { fg = 'gray' },
  CinderGroveFgDim = { fg = 'fg_dim' },
  CinderGroveFg = { fg = 'fg' },
  CinderGroveFgBright = { fg = 'fg_bright' },
  CinderGroveRed = { fg = 'red' },
  CinderGroveGreen = { fg = 'green' },
  CinderGroveYellow = { fg = 'yellow' },
  CinderGroveBlue = { fg = 'blue' },
  CinderGroveMagenta = { fg = 'magenta' },
  CinderGroveCyan = { fg = 'cyan' },
  CinderGroveOrange = { fg = 'orange' },

  Normal = { fg = 'fg', bg = 'bg' },
  NormalNC = { fg = 'fg', bg = 'bg' },
  NormalFloat = { fg = 'fg', bg = 'bg_alt' },
  FloatBorder = { fg = 'blue', bg = 'bg_alt' },
  FloatTitle = { fg = 'fg_bright', bg = 'bg_alt', bold = true },
  FloatFooter = { fg = 'gray', bg = 'bg_alt' },
  FloatShadow = { bg = 'bg', blend = 55 },
  FloatShadowThrough = { bg = 'bg', blend = 85 },

  Cursor = { fg = 'bg', bg = 'fg_bright' },
  CursorIM = { link = 'Cursor' },
  lCursor = { link = 'Cursor' },
  TermCursor = { link = 'Cursor' },
  TermCursorNC = { fg = 'bg', bg = 'gray' },
  CursorColumn = { bg = 'surface' },
  CursorLine = { bg = 'surface' },
  CursorLineNr = { fg = 'yellow', bg = 'surface', bold = true },
  CursorLineSign = { bg = 'surface' },
  CursorLineFold = { bg = 'surface' },
  LineNr = { fg = 'muted', bg = 'bg' },
  LineNrAbove = { link = 'LineNr' },
  LineNrBelow = { link = 'LineNr' },
  SignColumn = { bg = 'bg' },
  ColorColumn = { bg = 'surface' },
  Conceal = { fg = 'gray' },

  Visual = { bg = 'muted' },
  VisualNOS = { bg = 'muted' },
  Search = { fg = 'bg', bg = 'yellow' },
  IncSearch = { fg = 'bg', bg = 'blue', bold = true },
  CurSearch = { link = 'IncSearch' },
  Substitute = { fg = 'bg', bg = 'magenta' },
  MatchParen = { fg = 'yellow', bold = true, underline = true },

  Pmenu = { fg = 'fg', bg = 'bg_alt' },
  PmenuSel = { fg = 'fg_bright', bg = 'muted' },
  PmenuKind = { fg = 'cyan', bg = 'bg_alt' },
  PmenuKindSel = { fg = 'cyan', bg = 'muted' },
  PmenuExtra = { fg = 'gray', bg = 'bg_alt' },
  PmenuExtraSel = { fg = 'fg_dim', bg = 'muted' },
  PmenuSbar = { bg = 'surface' },
  PmenuThumb = { bg = 'muted' },
  PmenuMatch = { fg = 'blue', bg = 'bg_alt', bold = true },
  PmenuMatchSel = { fg = 'yellow', bg = 'muted', bold = true },
  ComplMatchIns = { fg = 'gray' },
  SnippetTabstop = { bg = 'surface' },

  StatusLine = { fg = 'fg_bright', bg = 'muted' },
  StatusLineNC = { fg = 'gray', bg = 'surface' },
  StatusLineTerm = { link = 'StatusLine' },
  StatusLineTermNC = { link = 'StatusLineNC' },
  TabLine = { fg = 'fg', bg = 'surface' },
  TabLineFill = { bg = 'bg_alt' },
  TabLineSel = { fg = 'fg_bright', bg = 'muted', bold = true },
  WinSeparator = { fg = 'muted' },
  VertSplit = { link = 'WinSeparator' },
  WinBar = { fg = 'fg_dim', bg = 'bg', bold = true },
  WinBarNC = { fg = 'muted', bg = 'bg' },
  ToolbarLine = { bg = 'bg_alt' },
  ToolbarButton = { fg = 'bg', bg = 'blue', bold = true },

  Folded = { fg = 'gray', bg = 'surface' },
  FoldColumn = { fg = 'muted', bg = 'bg' },
  QuickFixLine = { bg = 'surface', bold = true },
  qfLineNr = { fg = 'yellow' },
  qfFileName = { fg = 'blue' },

  Directory = { fg = 'blue' },
  Title = { fg = 'magenta', bold = true },
  Question = { fg = 'green' },
  MoreMsg = { fg = 'cyan' },
  ModeMsg = { fg = 'fg_dim', bold = true },
  WarningMsg = { fg = 'yellow' },
  ErrorMsg = { fg = 'red', bold = true },
  MsgArea = { fg = 'fg' },
  MsgSeparator = { fg = 'muted', bg = 'surface' },

  NonText = { fg = 'muted' },
  EndOfBuffer = { fg = 'muted', bg = 'bg' },
  SpecialKey = { fg = 'muted' },
  Whitespace = { fg = 'muted' },
  WildMenu = { fg = 'bg', bg = 'yellow' },

  SpellBad = { undercurl = true, sp = 'red' },
  SpellCap = { undercurl = true, sp = 'blue' },
  SpellLocal = { undercurl = true, sp = 'cyan' },
  SpellRare = { undercurl = true, sp = 'magenta' },

  Added = { fg = 'green' },
  Changed = { fg = 'cyan' },
  Removed = { fg = 'red' },
  DiffAdd = { fg = 'green', bg = 'surface' },
  DiffChange = { fg = 'cyan', bg = 'surface' },
  DiffDelete = { fg = 'red', bg = 'surface' },
  DiffText = { fg = 'yellow', bg = 'muted', bold = true },

  healthError = { fg = 'red' },
  healthSuccess = { fg = 'green' },
  healthWarning = { fg = 'yellow' },
  NvimInternalError = { fg = 'bg', bg = 'red' },
  RedrawDebugClear = { fg = 'bg', bg = 'yellow' },
  RedrawDebugComposed = { fg = 'bg', bg = 'green' },
  RedrawDebugNormal = { reverse = true },
  RedrawDebugRecompose = { fg = 'bg', bg = 'red' },
}
