return {
  CinderGroveBackground = { fg = 'background' },
  CinderGroveContainer = { fg = 'container' },
  CinderGroveSurface = { fg = 'surface' },
  CinderGroveOverlay = { fg = 'overlay' },
  CinderGroveTextMuted = { fg = 'text_muted' },
  CinderGroveTextSubtle = { fg = 'text_subtle' },
  CinderGroveTextSecondary = { fg = 'text_secondary' },
  CinderGroveText = { fg = 'text' },
  CinderGroveTextBright = { fg = 'text_bright' },
  CinderGrovePrimary = { fg = 'primary' },
  CinderGroveSecondary = { fg = 'secondary' },
  CinderGroveError = { fg = 'error' },
  CinderGroveWarning = { fg = 'warning' },
  CinderGroveSuccess = { fg = 'success' },
  CinderGroveInfo = { fg = 'info' },
  CinderGrovePurple = { fg = 'purple' },
  CinderGroveCyan = { fg = 'cyan' },

  Normal = { fg = 'text', bg = 'background' },
  NormalNC = { fg = 'text', bg = 'background' },
  NormalFloat = { fg = 'text', bg = 'container' },
  FloatBorder = { fg = 'info', bg = 'container' },
  FloatTitle = { fg = 'text_bright', bg = 'container', bold = true },
  FloatFooter = { fg = 'text_subtle', bg = 'container' },
  FloatShadow = { bg = 'background', blend = 55 },
  FloatShadowThrough = { bg = 'background', blend = 85 },

  Cursor = { fg = 'background', bg = 'text_bright' },
  CursorIM = { link = 'Cursor' },
  lCursor = { link = 'Cursor' },
  TermCursor = { link = 'Cursor' },
  TermCursorNC = { fg = 'background', bg = 'text_subtle' },
  CursorColumn = { bg = 'surface' },
  CursorLine = { bg = 'surface' },
  CursorLineNr = { fg = 'warning', bg = 'surface', bold = true },
  CursorLineSign = { bg = 'surface' },
  CursorLineFold = { bg = 'surface' },
  LineNr = { fg = 'text_muted', bg = 'background' },
  LineNrAbove = { link = 'LineNr' },
  LineNrBelow = { link = 'LineNr' },
  SignColumn = { bg = 'background' },
  ColorColumn = { bg = 'surface' },
  Conceal = { fg = 'text_subtle' },

  Visual = { bg = 'overlay' },
  VisualNOS = { bg = 'overlay' },
  Search = { fg = 'background', bg = 'warning' },
  IncSearch = { fg = 'background', bg = 'info', bold = true },
  CurSearch = { link = 'IncSearch' },
  Substitute = { fg = 'background', bg = 'purple' },
  MatchParen = { fg = 'warning', bold = true, underline = true },

  Pmenu = { fg = 'text', bg = 'container' },
  PmenuSel = { fg = 'text_bright', bg = 'overlay' },
  PmenuKind = { fg = 'cyan', bg = 'container' },
  PmenuKindSel = { fg = 'cyan', bg = 'overlay' },
  PmenuExtra = { fg = 'text_subtle', bg = 'container' },
  PmenuExtraSel = { fg = 'text_secondary', bg = 'overlay' },
  PmenuSbar = { bg = 'surface' },
  PmenuThumb = { bg = 'overlay' },
  PmenuMatch = { fg = 'info', bg = 'container', bold = true },
  PmenuMatchSel = { fg = 'warning', bg = 'overlay', bold = true },
  ComplMatchIns = { fg = 'text_subtle' },
  SnippetTabstop = { bg = 'surface' },

  StatusLine = { fg = 'text_bright', bg = 'overlay' },
  StatusLineNC = { fg = 'text_subtle', bg = 'surface' },
  StatusLineTerm = { link = 'StatusLine' },
  StatusLineTermNC = { link = 'StatusLineNC' },
  TabLine = { fg = 'text', bg = 'surface' },
  TabLineFill = { bg = 'container' },
  TabLineSel = { fg = 'text_bright', bg = 'overlay', bold = true },
  WinSeparator = { fg = 'text_muted' },
  VertSplit = { link = 'WinSeparator' },
  WinBar = { fg = 'text_secondary', bg = 'background', bold = true },
  WinBarNC = { fg = 'text_muted', bg = 'background' },
  ToolbarLine = { bg = 'container' },
  ToolbarButton = { fg = 'background', bg = 'info', bold = true },

  Folded = { fg = 'text_subtle', bg = 'surface' },
  FoldColumn = { fg = 'text_muted', bg = 'background' },
  QuickFixLine = { bg = 'surface', bold = true },
  qfLineNr = { fg = 'warning' },
  qfFileName = { fg = 'info' },

  Directory = { fg = 'info' },
  Title = { fg = 'purple', bold = true },
  Question = { fg = 'primary' },
  MoreMsg = { fg = 'cyan' },
  ModeMsg = { fg = 'text_secondary', bold = true },
  WarningMsg = { fg = 'warning' },
  ErrorMsg = { fg = 'error', bold = true },
  MsgArea = { fg = 'text' },
  MsgSeparator = { fg = 'text_muted', bg = 'surface' },

  NonText = { fg = 'text_muted' },
  EndOfBuffer = { fg = 'text_muted', bg = 'background' },
  SpecialKey = { fg = 'text_muted' },
  Whitespace = { fg = 'text_muted' },
  WildMenu = { fg = 'background', bg = 'warning' },

  SpellBad = { undercurl = true, sp = 'error' },
  SpellCap = { undercurl = true, sp = 'info' },
  SpellLocal = { undercurl = true, sp = 'cyan' },
  SpellRare = { undercurl = true, sp = 'purple' },

  Added = { fg = 'success' },
  Changed = { fg = 'cyan' },
  Removed = { fg = 'error' },
  DiffAdd = { fg = 'success', bg = 'surface' },
  DiffChange = { fg = 'cyan', bg = 'surface' },
  DiffDelete = { fg = 'error', bg = 'surface' },
  DiffText = { fg = 'warning', bg = 'overlay', bold = true },

  healthError = { fg = 'error' },
  healthSuccess = { fg = 'success' },
  healthWarning = { fg = 'warning' },
  NvimInternalError = { fg = 'background', bg = 'error' },
  RedrawDebugClear = { fg = 'background', bg = 'warning' },
  RedrawDebugComposed = { fg = 'background', bg = 'success' },
  RedrawDebugNormal = { reverse = true },
  RedrawDebugRecompose = { fg = 'background', bg = 'error' },
}
