return {
  markdownHeadingDelimiter = { fg = 'green', bold = true },
  markdownH1 = { fg = 'green', bold = true },
  markdownH2 = { fg = 'green', bold = true },
  markdownH3 = { fg = 'green', bold = true },
  markdownH4 = { fg = 'green', bold = true },
  markdownH5 = { fg = 'green', bold = true },
  markdownH6 = { fg = 'green', bold = true },
  markdownCode = { fg = 'fg_bright', bg = 'bg_alt' },
  markdownCodeBlock = { fg = 'fg_bright', bg = 'bg_alt' },
  markdownCodeDelimiter = { fg = 'gray' },
  markdownLinkText = { fg = 'green', underline = true },
  markdownUrl = { fg = 'blue', underline = true },
  markdownLinkTextDelimiter = { fg = 'muted' },
  markdownLinkDelimiter = { fg = 'muted' },
  markdownListMarker = { fg = 'orange' },
  markdownOrderedListMarker = { fg = 'orange' },
  markdownBlockquote = { fg = 'yellow' },
  markdownRule = { fg = 'yellow' },
  markdownBold = { bold = true },
  markdownItalic = { italic = true },
  markdownBoldItalic = { bold = true, italic = true },
  markdownEscape = { fg = 'fg_bright' },
  markdownError = { fg = 'red' },

  jsonKeyword = { fg = 'fg_bright' },
  jsonQuote = { fg = 'gray' },
  jsonBraces = { fg = 'muted' },
  jsonNull = { fg = 'cyan' },
  jsonBoolean = { fg = 'cyan' },
  yamlKeyValueDelimiter = { fg = 'blue' },
  yamlBlockCollectionItemStart = { fg = 'orange' },
  yamlAnchor = { fg = 'yellow' },
  yamlAlias = { fg = 'yellow' },
  yamlDocumentStart = { fg = 'cyan' },
  yamlTag = { fg = 'magenta' },
  tomlKey = { fg = 'fg_bright' },
  tomlTable = { fg = 'blue', bold = true },
  tomlTableArray = { fg = 'blue', bold = true },
  tomlDate = { fg = 'cyan' },
  tomlBoolean = { fg = 'cyan' },
  dosiniLabel = { fg = 'blue', bold = true },

  htmlTag = { fg = 'muted' },
  htmlEndTag = { fg = 'muted' },
  htmlTagName = { fg = 'blue', italic = true },
  htmlSpecialTagName = { fg = 'blue', italic = true },
  htmlArg = { fg = 'green' },
  htmlLink = { fg = 'blue', underline = true },
  htmlBold = { bold = true },
  htmlItalic = { italic = true },
  cssBraces = { fg = 'muted' },
  cssClassName = { fg = 'fg_dim' },
  cssIdentifier = { fg = 'fg_dim' },
  cssProp = { fg = 'fg_bright' },
  cssFunctionName = { fg = 'fg_bright', bold = true },
  cssColor = { fg = 'cyan' },
  cssUnitDecorators = { fg = 'cyan' },
  cssImportant = { fg = 'magenta', bold = true },

  luaFuncCall = { fg = 'fg_bright', bold = true },
  luaFunction = { fg = 'magenta' },
  luaTable = { fg = 'fg_bright' },
  luaConstant = { fg = 'cyan' },
  luaBuiltIn = { fg = 'cyan', italic = true },
  luaDocTag = { fg = 'gray', italic = true },
  luaDocIdentifier = { fg = 'gray', italic = true },

  goPackage = { fg = 'magenta' },
  goImport = { fg = 'magenta' },
  goVar = { fg = 'magenta' },
  goConst = { fg = 'magenta' },
  goType = { fg = 'magenta' },
  goBuiltins = { fg = 'fg_bright', bold = true },
  goFormatSpecifier = { fg = 'fg_bright' },
  goGenerateVariables = { fg = 'orange', italic = true },
  ['@comment.directive.go'] = { fg = 'magenta', italic = true },
  ['@comment.documentation.go'] = { fg = 'gray', italic = true },
  ['@lsp.type.namespace.go'] = { fg = 'blue', bold = true },

  pythonBuiltin = { fg = 'fg_bright', bold = true },
  pythonFunction = { fg = 'fg_bright', bold = true },
  pythonDecorator = { fg = 'muted', italic = true },
  pythonDecoratorName = { fg = 'fg_bright', bold = true },
  pythonExceptions = { fg = 'fg_bright', bold = true },
  pythonSelf = { fg = 'cyan', italic = true },
  ['@variable.builtin.python'] = { fg = 'cyan', italic = true },
  ['@function.builtin.python'] = { fg = 'fg_bright', bold = true },

  rustAttribute = { fg = 'fg_dim', italic = true },
  rustDerive = { fg = 'magenta', italic = true },
  rustMacro = { fg = 'magenta', italic = true },
  rustModPath = { fg = 'blue', bold = true },
  rustSelf = { fg = 'cyan', italic = true },
  rustEnum = { fg = 'cyan', italic = true },
  rustEnumVariant = { fg = 'orange' },
  ['@attribute.rust'] = { fg = 'fg_dim', italic = true },
  ['@function.macro.rust'] = { fg = 'magenta', italic = true },
  ['@lsp.type.enumMember.rust'] = { fg = 'orange' },

  shShellVariables = { fg = 'blue', italic = true },
  shVariable = { fg = 'blue' },
  shFunction = { fg = 'fg_bright', bold = true },
  shFunctionKey = { fg = 'magenta' },
  shDeref = { fg = 'fg_bright' },
  shCommandSub = { fg = 'fg_bright', bold = true },
  shQuote = { fg = 'green' },
  shOption = { fg = 'orange' },

  javascriptBraces = { fg = 'muted' },
  javascriptFunction = { fg = 'magenta' },
  javascriptIdentifier = { fg = 'fg' },
  javascriptNull = { fg = 'cyan' },
  javascriptNumber = { fg = 'cyan' },
  javascriptObjectLabel = { fg = 'fg_bright' },
  javascriptTemplate = { fg = 'green' },
  typescriptTypeReference = { fg = 'cyan', italic = true },
  typescriptBraces = { fg = 'muted' },
  typescriptFuncKeyword = { fg = 'magenta' },
  ['@lsp.type.property.typescript'] = { fg = 'fg_bright' },
  ['@lsp.type.property.javascript'] = { fg = 'fg_bright' },
}
