return {
  DiagnosticError = { fg = 'red' },
  DiagnosticWarn = { fg = 'yellow' },
  DiagnosticInfo = { fg = 'blue' },
  DiagnosticHint = { fg = 'cyan' },
  DiagnosticOk = { fg = 'green' },

  DiagnosticSignError = { link = 'DiagnosticError' },
  DiagnosticSignWarn = { link = 'DiagnosticWarn' },
  DiagnosticSignInfo = { link = 'DiagnosticInfo' },
  DiagnosticSignHint = { link = 'DiagnosticHint' },
  DiagnosticSignOk = { link = 'DiagnosticOk' },

  DiagnosticVirtualTextError = { fg = 'red', bg = 'surface' },
  DiagnosticVirtualTextWarn = { fg = 'yellow', bg = 'surface' },
  DiagnosticVirtualTextInfo = { fg = 'blue', bg = 'surface' },
  DiagnosticVirtualTextHint = { fg = 'cyan', bg = 'surface' },
  DiagnosticVirtualTextOk = { fg = 'green', bg = 'surface' },

  DiagnosticFloatingError = { link = 'DiagnosticError' },
  DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
  DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
  DiagnosticFloatingHint = { link = 'DiagnosticHint' },
  DiagnosticFloatingOk = { link = 'DiagnosticOk' },

  DiagnosticUnderlineError = { undercurl = true, sp = 'red' },
  DiagnosticUnderlineWarn = { undercurl = true, sp = 'yellow' },
  DiagnosticUnderlineInfo = { undercurl = true, sp = 'blue' },
  DiagnosticUnderlineHint = { undercurl = true, sp = 'cyan' },
  DiagnosticUnderlineOk = { undercurl = true, sp = 'green' },
  DiagnosticDeprecated = { strikethrough = true, sp = 'gray' },
  DiagnosticUnnecessary = { fg = 'muted' },

  LspReferenceText = { bg = 'surface' },
  LspReferenceRead = { bg = 'surface' },
  LspReferenceWrite = { bg = 'surface', underline = true },
  LspCodeLens = { fg = 'muted' },
  LspCodeLensSeparator = { fg = 'muted' },
  LspInlayHint = { fg = 'gray', bg = 'surface', italic = true },
  LspSignatureActiveParameter = { fg = 'yellow', bold = true },

  ['@lsp.type.class'] = { link = '@type' },
  ['@lsp.type.comment'] = { link = '@comment' },
  ['@lsp.type.decorator'] = { link = '@attribute' },
  ['@lsp.type.enum'] = { link = '@type' },
  ['@lsp.type.enumMember'] = { fg = 'orange' },
  ['@lsp.type.event'] = { fg = 'yellow' },
  ['@lsp.type.function'] = { link = '@function' },
  ['@lsp.type.interface'] = { link = '@type' },
  ['@lsp.type.keyword'] = { link = '@keyword' },
  ['@lsp.type.macro'] = { link = '@function.macro' },
  ['@lsp.type.method'] = { link = '@function.method' },
  ['@lsp.type.modifier'] = { link = '@keyword.modifier' },
  ['@lsp.type.namespace'] = { link = '@module' },
  ['@lsp.type.number'] = { link = '@number' },
  ['@lsp.type.operator'] = { link = '@operator' },
  ['@lsp.type.parameter'] = { link = '@variable.parameter' },
  ['@lsp.type.property'] = { link = '@property' },
  ['@lsp.type.regexp'] = { link = '@string.regexp' },
  ['@lsp.type.string'] = { link = '@string' },
  ['@lsp.type.struct'] = { link = '@type' },
  ['@lsp.type.type'] = { link = '@type' },
  ['@lsp.type.typeParameter'] = { fg = 'cyan', italic = true },
  ['@lsp.type.variable'] = { link = '@variable' },
  ['@lsp.mod.deprecated'] = { strikethrough = true },
  ['@lsp.mod.readonly'] = { fg = 'cyan' },
  ['@lsp.mod.defaultLibrary'] = { italic = true },
}
