return {
  Comment = { fg = 'text_muted', italic = true },
  Constant = { fg = 'cyan' },
  String = { fg = 'primary' },
  Character = { fg = 'primary' },
  Number = { fg = 'cyan' },
  Boolean = { fg = 'cyan' },
  Float = { fg = 'cyan' },
  Identifier = { fg = 'text' },
  Function = { fg = 'text_bright', bold = true },
  Statement = { fg = 'purple' },
  Conditional = { fg = 'purple' },
  Repeat = { fg = 'purple' },
  Label = { fg = 'purple' },
  Operator = { fg = 'secondary' },
  Keyword = { fg = 'purple' },
  Exception = { fg = 'purple' },
  PreProc = { fg = 'purple' },
  Include = { fg = 'purple' },
  Define = { fg = 'purple' },
  Macro = { fg = 'purple' },
  PreCondit = { fg = 'purple' },
  Type = { fg = 'cyan', italic = true },
  StorageClass = { fg = 'purple' },
  Structure = { fg = 'cyan', italic = true },
  Typedef = { fg = 'cyan', italic = true },
  Special = { fg = 'info' },
  SpecialChar = { fg = 'warning' },
  Tag = { fg = 'info', italic = true },
  Delimiter = { fg = 'info' },
  SpecialComment = { fg = 'text_subtle', italic = true },
  Debug = { fg = 'error' },
  Underlined = { fg = 'info', underline = true },
  Ignore = { fg = 'text_muted' },
  Error = { fg = 'error', bold = true },
  Todo = { fg = 'warning', bold = true },
}
