return {
  Comment = { fg = 'muted', italic = true },
  Constant = { fg = 'cyan' },
  String = { fg = 'green' },
  Character = { fg = 'green' },
  Number = { fg = 'cyan' },
  Boolean = { fg = 'cyan' },
  Float = { fg = 'cyan' },
  Identifier = { fg = 'fg' },
  Function = { fg = 'fg_bright', bold = true },
  Statement = { fg = 'magenta' },
  Conditional = { fg = 'magenta' },
  Repeat = { fg = 'magenta' },
  Label = { fg = 'magenta' },
  Operator = { fg = 'orange' },
  Keyword = { fg = 'magenta' },
  Exception = { fg = 'magenta' },
  PreProc = { fg = 'magenta' },
  Include = { fg = 'magenta' },
  Define = { fg = 'magenta' },
  Macro = { fg = 'magenta' },
  PreCondit = { fg = 'magenta' },
  Type = { fg = 'cyan', italic = true },
  StorageClass = { fg = 'magenta' },
  Structure = { fg = 'cyan', italic = true },
  Typedef = { fg = 'cyan', italic = true },
  Special = { fg = 'blue' },
  SpecialChar = { fg = 'yellow' },
  Tag = { fg = 'blue', italic = true },
  Delimiter = { fg = 'blue' },
  SpecialComment = { fg = 'gray', italic = true },
  Debug = { fg = 'red' },
  Underlined = { fg = 'blue', underline = true },
  Ignore = { fg = 'muted' },
  Error = { fg = 'red', bold = true },
  Todo = { fg = 'yellow', bold = true },
}
