return {
  ['@none'] = { fg = 'fg' },
  ['@variable'] = { fg = 'fg' },
  ['@variable.builtin'] = { fg = 'cyan', italic = true },
  ['@variable.parameter'] = { fg = 'blue', italic = true },
  ['@variable.parameter.builtin'] = { fg = 'cyan', italic = true },
  ['@variable.member'] = { fg = 'fg_bright' },

  ['@constant'] = { fg = 'cyan' },
  ['@constant.builtin'] = { fg = 'cyan' },
  ['@constant.macro'] = { fg = 'magenta' },
  ['@module'] = { fg = 'blue', bold = true },
  ['@module.builtin'] = { fg = 'blue', italic = true },
  ['@label'] = { fg = 'magenta' },

  ['@string'] = { fg = 'green' },
  ['@string.documentation'] = { fg = 'gray', italic = true },
  ['@string.regexp'] = { fg = 'green' },
  ['@string.escape'] = { fg = 'fg_bright' },
  ['@string.special'] = { fg = 'yellow' },
  ['@string.special.symbol'] = { fg = 'orange' },
  ['@string.special.path'] = { fg = 'blue', underline = true },
  ['@string.special.url'] = { fg = 'blue', underline = true },
  ['@character'] = { fg = 'green' },
  ['@character.special'] = { fg = 'fg_bright' },
  ['@boolean'] = { fg = 'cyan' },
  ['@number'] = { fg = 'cyan' },
  ['@number.float'] = { fg = 'cyan' },

  ['@type'] = { fg = 'cyan', italic = true },
  ['@type.builtin'] = { fg = 'cyan' },
  ['@type.definition'] = { fg = 'cyan', italic = true },
  ['@attribute'] = { fg = 'magenta' },
  ['@attribute.builtin'] = { fg = 'gray', italic = true },
  ['@property'] = { fg = 'fg_bright' },

  ['@function'] = { fg = 'fg_bright', bold = true },
  ['@function.builtin'] = { fg = 'fg_bright', bold = true },
  ['@function.call'] = { fg = 'fg_bright', bold = true },
  ['@function.macro'] = { fg = 'magenta', italic = true },
  ['@function.method'] = { fg = 'fg_bright', bold = true },
  ['@function.method.call'] = { fg = 'fg_bright', bold = true },
  ['@constructor'] = { fg = 'fg_bright', italic = true },
  ['@operator'] = { fg = 'orange' },

  ['@keyword'] = { fg = 'magenta' },
  ['@keyword.coroutine'] = { fg = 'magenta' },
  ['@keyword.function'] = { fg = 'magenta' },
  ['@keyword.operator'] = { fg = 'magenta' },
  ['@keyword.import'] = { fg = 'magenta' },
  ['@keyword.type'] = { fg = 'magenta' },
  ['@keyword.modifier'] = { fg = 'magenta' },
  ['@keyword.repeat'] = { fg = 'magenta' },
  ['@keyword.return'] = { fg = 'magenta' },
  ['@keyword.debug'] = { fg = 'red' },
  ['@keyword.exception'] = { fg = 'magenta' },
  ['@keyword.conditional'] = { fg = 'magenta' },
  ['@keyword.conditional.ternary'] = { fg = 'orange' },
  ['@keyword.directive'] = { fg = 'magenta' },
  ['@keyword.directive.define'] = { fg = 'magenta' },

  ['@punctuation'] = { fg = 'blue' },
  ['@punctuation.delimiter'] = { fg = 'blue' },
  ['@punctuation.bracket'] = { fg = 'muted' },
  ['@punctuation.special'] = { fg = 'yellow' },

  ['@comment'] = { link = 'Comment' },
  ['@comment.documentation'] = { fg = 'gray', italic = true },
  ['@comment.error'] = { fg = 'red', bold = true },
  ['@comment.warning'] = { fg = 'yellow', bold = true },
  ['@comment.todo'] = { fg = 'yellow', bold = true },
  ['@comment.note'] = { fg = 'blue', bold = true },

  ['@markup.strong'] = { bold = true },
  ['@markup.italic'] = { italic = true },
  ['@markup.strikethrough'] = { strikethrough = true },
  ['@markup.underline'] = { underline = true },
  ['@markup.heading'] = { fg = 'green', bold = true },
  ['@markup.heading.1'] = { fg = 'green', bold = true },
  ['@markup.heading.2'] = { fg = 'green', bold = true },
  ['@markup.heading.3'] = { fg = 'green', bold = true },
  ['@markup.heading.4'] = { fg = 'green', bold = true },
  ['@markup.heading.5'] = { fg = 'green', bold = true },
  ['@markup.heading.6'] = { fg = 'green', bold = true },
  ['@markup.quote'] = { fg = 'yellow' },
  ['@markup.math'] = { fg = 'blue' },
  ['@markup.link'] = { fg = 'green', underline = true },
  ['@markup.link.label'] = { fg = 'green', italic = true },
  ['@markup.link.url'] = { fg = 'blue', underline = true },
  ['@markup.raw'] = { fg = 'fg_bright', bg = 'bg_alt' },
  ['@markup.raw.block'] = { fg = 'fg_bright', bg = 'bg_alt' },
  ['@markup.list'] = { fg = 'orange' },
  ['@markup.list.checked'] = { fg = 'green' },
  ['@markup.list.unchecked'] = { fg = 'gray' },

  ['@diff.plus'] = { fg = 'green' },
  ['@diff.minus'] = { fg = 'red' },
  ['@diff.delta'] = { fg = 'cyan' },

  ['@tag'] = { fg = 'blue', italic = true },
  ['@tag.builtin'] = { fg = 'blue', italic = true },
  ['@tag.attribute'] = { fg = 'green' },
  ['@tag.delimiter'] = { fg = 'muted' },

  ['@field'] = { link = '@variable.member' },
  ['@namespace'] = { link = '@module' },
  ['@namespace.builtin'] = { link = '@module.builtin' },
  ['@parameter'] = { link = '@variable.parameter' },
  ['@method'] = { link = '@function.method' },
  ['@method.call'] = { link = '@function.method.call' },
  ['@float'] = { link = '@number.float' },
  ['@define'] = { link = '@keyword.directive.define' },
  ['@exception'] = { link = '@keyword.exception' },
  ['@include'] = { link = '@keyword.import' },
  ['@macro'] = { link = '@function.macro' },
  ['@preproc'] = { link = '@keyword.directive' },
  ['@repeat'] = { link = '@keyword.repeat' },
  ['@storageclass'] = { link = '@keyword.modifier' },
  ['@structure'] = { link = '@type' },
  ['@conditional'] = { link = '@keyword.conditional' },

  ['@text.literal'] = { link = '@markup.raw' },
  ['@text.reference'] = { link = '@markup.link' },
  ['@text.title'] = { link = '@markup.heading' },
  ['@text.uri'] = { link = '@markup.link.url' },
  ['@text.underline'] = { link = '@markup.underline' },
  ['@text.todo'] = { link = '@comment.todo' },
  ['@text.emphasis'] = { link = '@markup.italic' },
  ['@text.strong'] = { link = '@markup.strong' },
  ['@text.strike'] = { link = '@markup.strikethrough' },
  ['@text.math'] = { link = '@markup.math' },
  ['@text.note'] = { link = '@comment.note' },
  ['@text.warning'] = { link = '@comment.warning' },
  ['@text.danger'] = { link = '@comment.error' },
}
