return {
  BlinkCmpMenu = { fg = 'fg', bg = 'bg_alt' },
  BlinkCmpMenuBorder = { fg = 'blue', bg = 'bg_alt' },
  BlinkCmpMenuSelection = { fg = 'fg_bright', bg = 'muted' },
  BlinkCmpScrollBarThumb = { bg = 'muted' },
  BlinkCmpScrollBarGutter = { bg = 'surface' },
  BlinkCmpLabel = { fg = 'fg' },
  BlinkCmpLabelDeprecated = { fg = 'muted', strikethrough = true },
  BlinkCmpLabelMatch = { fg = 'blue', bold = true },
  BlinkCmpLabelDetail = { fg = 'gray' },
  BlinkCmpLabelDescription = { fg = 'gray' },
  BlinkCmpKind = { fg = 'cyan' },
  BlinkCmpSource = { fg = 'muted' },
  BlinkCmpGhostText = { fg = 'muted', italic = true },
  BlinkCmpDoc = { fg = 'fg', bg = 'bg_alt' },
  BlinkCmpDocBorder = { fg = 'blue', bg = 'bg_alt' },
  BlinkCmpDocSeparator = { fg = 'muted', bg = 'bg_alt' },
  BlinkCmpDocCursorLine = { bg = 'surface' },
  BlinkCmpSignatureHelp = { fg = 'fg', bg = 'bg_alt' },
  BlinkCmpSignatureHelpBorder = { fg = 'blue', bg = 'bg_alt' },
  BlinkCmpSignatureHelpActiveParameter = { fg = 'yellow', bold = true },

  CmpItemAbbr = { fg = 'fg' },
  CmpItemAbbrDeprecated = { fg = 'muted', strikethrough = true },
  CmpItemAbbrMatch = { fg = 'blue', bold = true },
  CmpItemAbbrMatchFuzzy = { fg = 'blue' },
  CmpItemMenu = { fg = 'gray' },
  CmpItemKind = { fg = 'cyan' },
  CmpDocumentation = { fg = 'fg', bg = 'bg_alt' },
  CmpDocumentationBorder = { fg = 'blue', bg = 'bg_alt' },
  CmpGhostText = { fg = 'muted', italic = true },
}
