return {
  BlinkCmpMenu = { fg = 'text', bg = 'container' },
  BlinkCmpMenuBorder = { fg = 'info', bg = 'container' },
  BlinkCmpMenuSelection = { fg = 'text_bright', bg = 'overlay' },
  BlinkCmpScrollBarThumb = { bg = 'overlay' },
  BlinkCmpScrollBarGutter = { bg = 'surface' },
  BlinkCmpLabel = { fg = 'text' },
  BlinkCmpLabelDeprecated = { fg = 'text_muted', strikethrough = true },
  BlinkCmpLabelMatch = { fg = 'info', bold = true },
  BlinkCmpLabelDetail = { fg = 'text_subtle' },
  BlinkCmpLabelDescription = { fg = 'text_subtle' },
  BlinkCmpKind = { fg = 'cyan' },
  BlinkCmpSource = { fg = 'text_muted' },
  BlinkCmpGhostText = { fg = 'text_muted', italic = true },
  BlinkCmpDoc = { fg = 'text', bg = 'container' },
  BlinkCmpDocBorder = { fg = 'info', bg = 'container' },
  BlinkCmpDocSeparator = { fg = 'text_muted', bg = 'container' },
  BlinkCmpDocCursorLine = { bg = 'surface' },
  BlinkCmpSignatureHelp = { fg = 'text', bg = 'container' },
  BlinkCmpSignatureHelpBorder = { fg = 'info', bg = 'container' },
  BlinkCmpSignatureHelpActiveParameter = { fg = 'warning', bold = true },

  CmpItemAbbr = { fg = 'text' },
  CmpItemAbbrDeprecated = { fg = 'text_muted', strikethrough = true },
  CmpItemAbbrMatch = { fg = 'info', bold = true },
  CmpItemAbbrMatchFuzzy = { fg = 'info' },
  CmpItemMenu = { fg = 'text_subtle' },
  CmpItemKind = { fg = 'cyan' },
  CmpDocumentation = { fg = 'text', bg = 'container' },
  CmpDocumentationBorder = { fg = 'info', bg = 'container' },
  CmpGhostText = { fg = 'text_muted', italic = true },
}
