return {
  FlashBackdrop = { link = 'Comment' },
  FlashMatch = { link = 'Search' },
  FlashCurrent = { link = 'IncSearch' },
  FlashLabel = { fg = 'bg', bg = 'yellow', bold = true },
  FlashPrompt = { link = 'MsgArea' },
  FlashPromptIcon = { link = 'Special' },
  FlashCursor = { link = 'Cursor' },

  FzfLuaNormal = { link = 'NormalFloat' },
  FzfLuaBorder = { link = 'FloatBorder' },
  FzfLuaTitle = { link = 'FloatTitle' },
  FzfLuaBackdrop = { bg = 'bg' },
  FzfLuaCursor = { link = 'IncSearch' },
  FzfLuaFzfCursorLine = { link = 'Visual' },
  FzfLuaPath = { fg = 'orange' },
  FzfLuaPathLineNr = { fg = 'blue' },
  FzfLuaPathColNr = { fg = 'blue' },
  FzfLuaHeaderBind = { fg = 'orange' },
  FzfLuaHeaderText = { fg = 'magenta' },
  FzfLuaBufNr = { fg = 'blue' },
  FzfLuaTabTitle = { fg = 'yellow' },
  FzfLuaTabMarker = { fg = 'yellow' },
  FzfLuaBufFlagAlt = { fg = 'blue' },
  FzfLuaFzfPointer = { fg = 'orange' },
  FzfLuaMatch = { fg = 'yellow', bold = true },
  FzfLuaLiveSym = { fg = 'blue' },

  TelescopeNormal = { fg = 'fg', bg = 'bg_alt' },
  TelescopeBorder = { link = 'FloatBorder' },
  TelescopeTitle = { fg = 'magenta', bold = true },
  TelescopePromptNormal = { fg = 'fg', bg = 'surface' },
  TelescopePromptBorder = { fg = 'blue', bg = 'surface' },
  TelescopePromptTitle = { fg = 'fg_bright', bg = 'surface', bold = true },
  TelescopePromptPrefix = { fg = 'orange' },
  TelescopePromptCounter = { fg = 'muted' },
  TelescopeResultsNormal = { fg = 'fg_dim', bg = 'bg_alt' },
  TelescopeResultsBorder = { link = 'FloatBorder' },
  TelescopeResultsTitle = { fg = 'gray', bg = 'bg_alt' },
  TelescopePreviewNormal = { fg = 'fg', bg = 'bg_alt' },
  TelescopePreviewBorder = { link = 'FloatBorder' },
  TelescopePreviewTitle = { fg = 'green', bg = 'bg_alt', bold = true },
  TelescopeSelection = { bg = 'surface' },
  TelescopeSelectionCaret = { fg = 'orange', bg = 'surface' },
  TelescopeMultiSelection = { fg = 'cyan' },
  TelescopeMatching = { fg = 'yellow', bold = true },

  WhichKey = { fg = 'orange' },
  WhichKeyGroup = { fg = 'magenta', bold = true },
  WhichKeyDesc = { fg = 'fg' },
  WhichKeyValue = { fg = 'gray' },
  WhichKeySeparator = { fg = 'muted' },
  WhichKeyTitle = { link = 'FloatTitle' },
  WhichKeyBorder = { link = 'FloatBorder' },
  WhichKeyNormal = { link = 'NormalFloat' },
  WhichKeyIconAzure = { fg = 'blue' },
  WhichKeyIconBlue = { fg = 'blue' },
  WhichKeyIconCyan = { fg = 'cyan' },
  WhichKeyIconGreen = { fg = 'green' },
  WhichKeyIconGrey = { fg = 'gray' },
  WhichKeyIconOrange = { fg = 'orange' },
  WhichKeyIconPurple = { fg = 'magenta' },
  WhichKeyIconRed = { fg = 'red' },
  WhichKeyIconYellow = { fg = 'yellow' },
}
