return {
  FlashBackdrop = { link = 'Comment' },
  FlashMatch = { link = 'Search' },
  FlashCurrent = { link = 'IncSearch' },
  FlashLabel = { fg = 'background', bg = 'warning', bold = true },
  FlashPrompt = { link = 'MsgArea' },
  FlashPromptIcon = { link = 'Special' },
  FlashCursor = { link = 'Cursor' },

  FzfLuaNormal = { link = 'NormalFloat' },
  FzfLuaBorder = { link = 'FloatBorder' },
  FzfLuaTitle = { link = 'FloatTitle' },
  FzfLuaBackdrop = { bg = 'background' },
  FzfLuaCursor = { link = 'IncSearch' },
  FzfLuaFzfCursorLine = { link = 'Visual' },
  FzfLuaPath = { fg = 'secondary' },
  FzfLuaPathLineNr = { fg = 'info' },
  FzfLuaPathColNr = { fg = 'info' },
  FzfLuaHeaderBind = { fg = 'secondary' },
  FzfLuaHeaderText = { fg = 'purple' },
  FzfLuaBufNr = { fg = 'info' },
  FzfLuaTabTitle = { fg = 'warning' },
  FzfLuaTabMarker = { fg = 'warning' },
  FzfLuaBufFlagAlt = { fg = 'info' },
  FzfLuaFzfPointer = { fg = 'secondary' },
  FzfLuaMatch = { fg = 'warning', bold = true },
  FzfLuaLiveSym = { fg = 'info' },

  TelescopeNormal = { fg = 'text', bg = 'container' },
  TelescopeBorder = { link = 'FloatBorder' },
  TelescopeTitle = { fg = 'purple', bold = true },
  TelescopePromptNormal = { fg = 'text', bg = 'surface' },
  TelescopePromptBorder = { fg = 'info', bg = 'surface' },
  TelescopePromptTitle = { fg = 'text_bright', bg = 'surface', bold = true },
  TelescopePromptPrefix = { fg = 'secondary' },
  TelescopePromptCounter = { fg = 'text_muted' },
  TelescopeResultsNormal = { fg = 'text_secondary', bg = 'container' },
  TelescopeResultsBorder = { link = 'FloatBorder' },
  TelescopeResultsTitle = { fg = 'text_subtle', bg = 'container' },
  TelescopePreviewNormal = { fg = 'text', bg = 'container' },
  TelescopePreviewBorder = { link = 'FloatBorder' },
  TelescopePreviewTitle = { fg = 'primary', bg = 'container', bold = true },
  TelescopeSelection = { bg = 'surface' },
  TelescopeSelectionCaret = { fg = 'secondary', bg = 'surface' },
  TelescopeMultiSelection = { fg = 'cyan' },
  TelescopeMatching = { fg = 'warning', bold = true },

  WhichKey = { fg = 'secondary' },
  WhichKeyGroup = { fg = 'purple', bold = true },
  WhichKeyDesc = { fg = 'text' },
  WhichKeyValue = { fg = 'text_subtle' },
  WhichKeySeparator = { fg = 'text_muted' },
  WhichKeyTitle = { link = 'FloatTitle' },
  WhichKeyBorder = { link = 'FloatBorder' },
  WhichKeyNormal = { link = 'NormalFloat' },
  WhichKeyIconAzure = { fg = 'info' },
  WhichKeyIconBlue = { fg = 'info' },
  WhichKeyIconCyan = { fg = 'cyan' },
  WhichKeyIconGreen = { fg = 'primary' },
  WhichKeyIconGrey = { fg = 'text_subtle' },
  WhichKeyIconOrange = { fg = 'secondary' },
  WhichKeyIconPurple = { fg = 'purple' },
  WhichKeyIconRed = { fg = 'error' },
  WhichKeyIconYellow = { fg = 'warning' },
}
