return {
  NeogitBranch = { fg = 'yellow' },
  NeogitBranchHead = { fg = 'yellow', bold = true },
  NeogitRemote = { fg = 'orange' },
  NeogitObjectId = { fg = 'magenta' },
  NeogitStash = { fg = 'cyan' },
  NeogitTagName = { fg = 'blue' },
  NeogitTagDistance = { fg = 'gray' },
  NeogitStatusHEAD = { fg = 'green', bold = true },
  NeogitFold = { fg = 'fg_bright' },
  NeogitRebaseDone = { fg = 'green' },
  NeogitSectionHeader = { fg = 'magenta', bold = true },
  NeogitSectionHeaderCount = { fg = 'blue' },
  NeogitChangeAdded = { fg = 'green' },
  NeogitChangeModified = { fg = 'yellow' },
  NeogitChangeDeleted = { fg = 'red' },
  NeogitChangeRenamed = { fg = 'orange' },
  NeogitChangeUpdated = { fg = 'cyan' },
  NeogitChangeCopied = { fg = 'blue' },
  NeogitChangeNewFile = { fg = 'green' },
  NeogitChangeUnmerged = { fg = 'red' },
  NeogitHunkHeader = { fg = 'fg_dim', bg = 'surface' },
  NeogitHunkHeaderHighlight = { fg = 'yellow', bg = 'surface', bold = true },
  NeogitHunkHeaderCursor = { fg = 'yellow', bg = 'surface', bold = true },
  NeogitDiffContext = { fg = 'fg_dim' },
  NeogitDiffContextHighlight = { fg = 'fg', bg = 'surface' },
  NeogitDiffContextCursor = { fg = 'fg', bg = 'surface', bold = true },
  NeogitDiffAdd = { fg = 'green' },
  NeogitDiffAddHighlight = { fg = 'green', bg = 'surface' },
  NeogitDiffAddCursor = { fg = 'green', bg = 'surface', bold = true },
  NeogitDiffDelete = { fg = 'red' },
  NeogitDiffDeleteHighlight = { fg = 'red', bg = 'surface' },
  NeogitDiffDeleteCursor = { fg = 'red', bg = 'surface', bold = true },
  NeogitDiffHeader = { fg = 'magenta' },
  NeogitDiffHeaderHighlight = { fg = 'blue', bold = true },
  NeogitDiffHeaderCursor = { fg = 'blue', bold = true },
  NeogitActiveItem = { bg = 'surface' },
  NeogitFilePath = { fg = 'blue' },
  NeogitCommitViewHeader = { fg = 'magenta', bold = true },
  NeogitGraphAuthor = { fg = 'orange' },
  NeogitGraphBlack = { fg = 'muted' },
  NeogitGraphBlackBold = { fg = 'muted', bold = true },
  NeogitGraphRed = { fg = 'red' },
  NeogitGraphRedBold = { fg = 'red', bold = true },
  NeogitGraphGreen = { fg = 'green' },
  NeogitGraphGreenBold = { fg = 'green', bold = true },
  NeogitGraphYellow = { fg = 'yellow' },
  NeogitGraphYellowBold = { fg = 'yellow', bold = true },
  NeogitGraphBlue = { fg = 'blue' },
  NeogitGraphBlueBold = { fg = 'blue', bold = true },
  NeogitGraphPurple = { fg = 'magenta' },
  NeogitGraphPurpleBold = { fg = 'magenta', bold = true },
  NeogitGraphCyan = { fg = 'cyan' },
  NeogitGraphCyanBold = { fg = 'cyan', bold = true },
  NeogitGraphWhite = { fg = 'fg' },
  NeogitGraphWhiteBold = { fg = 'fg', bold = true },
  NeogitGraphGray = { fg = 'gray' },
  NeogitGraphBoldGray = { fg = 'gray', bold = true },
  NeogitGraphOrange = { fg = 'orange' },
  NeogitSignatureGood = { fg = 'green' },
  NeogitSignatureBad = { fg = 'red' },
  NeogitSignatureMissing = { fg = 'magenta' },
  NeogitSignatureNone = { fg = 'gray' },
  NeogitSignatureGoodUnknown = { fg = 'green' },
  NeogitSignatureGoodExpired = { fg = 'yellow' },
  NeogitSignatureGoodExpiredKey = { fg = 'yellow' },
  NeogitSignatureGoodRevokedKey = { fg = 'orange' },
  NeogitPopupSectionTitle = { fg = 'magenta', bold = true },
  NeogitPopupBranchName = { fg = 'yellow' },
  NeogitPopupBold = { bold = true },
  NeogitPopupSwitchKey = { fg = 'yellow' },
  NeogitPopupSwitchEnabled = { fg = 'green' },
  NeogitPopupSwitchDisabled = { fg = 'muted' },
  NeogitPopupOptionKey = { fg = 'magenta' },
  NeogitPopupOptionEnabled = { fg = 'green' },
  NeogitPopupOptionDisabled = { fg = 'muted' },
  NeogitPopupConfigKey = { fg = 'blue' },
  NeogitPopupConfigEnabled = { fg = 'green' },
  NeogitPopupConfigDisabled = { fg = 'muted' },
  NeogitPopupActionKey = { fg = 'yellow' },
  NeogitPopupActionDisabled = { fg = 'muted' },
  NeogitCommandText = { fg = 'fg' },
  NeogitCommandTime = { fg = 'blue' },
  NeogitCommandCodeNormal = { fg = 'green' },
  NeogitCommandCodeError = { fg = 'red' },
  NeogitFloatHeader = { fg = 'magenta' },
  NeogitFloatHeaderHighlight = { fg = 'magenta', bold = true },
}
