return {
  TrailBlazerTrailMark = { fg = 'secondary', bold = true },
  TrailBlazerTrailMarkNext = { fg = 'warning', bold = true },
  TrailBlazerTrailMarkPrevious = { fg = 'info', bold = true },
  TrailBlazerTrailMarkCursor = { fg = 'background', bg = 'warning', bold = true },
  TrailBlazerTrailMarkNewest = { fg = 'background', bg = 'secondary', bold = true },
  TrailBlazerTrailMarkCustomOrd = { fg = 'text_bright', bg = 'info', bold = true },
  TrailBlazerTrailMarkGlobalChron = { fg = 'text_bright', bg = 'info', bold = true },
  TrailBlazerTrailMarkGlobalBufLineSorted = { fg = 'text_bright', bg = 'error', bold = true },
  TrailBlazerTrailMarkGlobalFpathLineSorted = { fg = 'text_bright', bg = 'error', bold = true },
  TrailBlazerTrailMarkGlobalChronBufLineSorted = { fg = 'background', bg = 'warning', bold = true },
  TrailBlazerTrailMarkGlobalChronFpathLineSorted = { fg = 'background', bg = 'warning', bold = true },
  TrailBlazerTrailMarkGlobalChronBufSwitchGroupChron = { fg = 'text_bright', bg = 'purple', bold = true },
  TrailBlazerTrailMarkGlobalChronBufSwitchGroupLineSorted = { fg = 'background', bg = 'cyan', bold = true },
  TrailBlazerTrailMarkBufferLocalChron = { fg = 'text_bright', bg = 'purple', bold = true },
  TrailBlazerTrailMarkBufferLocalLineSorted = { fg = 'background', bg = 'success', bold = true },
  TrailBlazerTrailMarkInverted = { fg = 'background', bg = 'secondary', bold = true },
  TrailBlazerTrailMarkNextInverted = { fg = 'background', bg = 'warning', bold = true },
  TrailBlazerTrailMarkPreviousInverted = { fg = 'background', bg = 'info', bold = true },
  TrailBlazerTrailMarkCursorInverted = { fg = 'warning', bg = 'background', bold = true },
  TrailBlazerTrailMarkNewestInverted = { fg = 'secondary', bg = 'background', bold = true },
  TrailBlazerTrailMarkCustomOrdInverted = { fg = 'info', bg = 'text_bright', bold = true },
  TrailBlazerTrailMarkGlobalChronInverted = { fg = 'info', bg = 'text_bright', bold = true },
  TrailBlazerTrailMarkGlobalBufLineSortedInverted = { fg = 'error', bg = 'text_bright', bold = true },
  TrailBlazerTrailMarkGlobalFpathLineSortedInverted = { fg = 'error', bg = 'text_bright', bold = true },
  TrailBlazerTrailMarkGlobalChronBufLineSortedInverted = { fg = 'warning', bg = 'background', bold = true },
  TrailBlazerTrailMarkGlobalChronFpathLineSortedInverted = { fg = 'warning', bg = 'background', bold = true },
  TrailBlazerTrailMarkGlobalChronBufSwitchGroupChronInverted = { fg = 'purple', bg = 'text_bright', bold = true },
  TrailBlazerTrailMarkGlobalChronBufSwitchGroupLineSortedInverted = { fg = 'cyan', bg = 'background', bold = true },
  TrailBlazerTrailMarkBufferLocalChronInverted = { fg = 'purple', bg = 'text_bright', bold = true },
  TrailBlazerTrailMarkBufferLocalLineSortedInverted = { fg = 'success', bg = 'background', bold = true },
}
