return {
  TrailBlazerTrailMark = { fg = 'orange', bold = true },
  TrailBlazerTrailMarkNext = { fg = 'yellow', bold = true },
  TrailBlazerTrailMarkPrevious = { fg = 'blue', bold = true },
  TrailBlazerTrailMarkCursor = { fg = 'bg', bg = 'yellow', bold = true },
  TrailBlazerTrailMarkNewest = { fg = 'bg', bg = 'orange', bold = true },
  TrailBlazerTrailMarkCustomOrd = { fg = 'fg_bright', bg = 'blue', bold = true },
  TrailBlazerTrailMarkGlobalChron = { fg = 'fg_bright', bg = 'blue', bold = true },
  TrailBlazerTrailMarkGlobalBufLineSorted = { fg = 'fg_bright', bg = 'red', bold = true },
  TrailBlazerTrailMarkGlobalFpathLineSorted = { fg = 'fg_bright', bg = 'red', bold = true },
  TrailBlazerTrailMarkGlobalChronBufLineSorted = { fg = 'bg', bg = 'yellow', bold = true },
  TrailBlazerTrailMarkGlobalChronFpathLineSorted = { fg = 'bg', bg = 'yellow', bold = true },
  TrailBlazerTrailMarkGlobalChronBufSwitchGroupChron = { fg = 'fg_bright', bg = 'magenta', bold = true },
  TrailBlazerTrailMarkGlobalChronBufSwitchGroupLineSorted = { fg = 'bg', bg = 'cyan', bold = true },
  TrailBlazerTrailMarkBufferLocalChron = { fg = 'fg_bright', bg = 'magenta', bold = true },
  TrailBlazerTrailMarkBufferLocalLineSorted = { fg = 'bg', bg = 'green', bold = true },
  TrailBlazerTrailMarkInverted = { fg = 'bg', bg = 'orange', bold = true },
  TrailBlazerTrailMarkNextInverted = { fg = 'bg', bg = 'yellow', bold = true },
  TrailBlazerTrailMarkPreviousInverted = { fg = 'bg', bg = 'blue', bold = true },
  TrailBlazerTrailMarkCursorInverted = { fg = 'yellow', bg = 'bg', bold = true },
  TrailBlazerTrailMarkNewestInverted = { fg = 'orange', bg = 'bg', bold = true },
  TrailBlazerTrailMarkCustomOrdInverted = { fg = 'blue', bg = 'fg_bright', bold = true },
  TrailBlazerTrailMarkGlobalChronInverted = { fg = 'blue', bg = 'fg_bright', bold = true },
  TrailBlazerTrailMarkGlobalBufLineSortedInverted = { fg = 'red', bg = 'fg_bright', bold = true },
  TrailBlazerTrailMarkGlobalFpathLineSortedInverted = { fg = 'red', bg = 'fg_bright', bold = true },
  TrailBlazerTrailMarkGlobalChronBufLineSortedInverted = { fg = 'yellow', bg = 'bg', bold = true },
  TrailBlazerTrailMarkGlobalChronFpathLineSortedInverted = { fg = 'yellow', bg = 'bg', bold = true },
  TrailBlazerTrailMarkGlobalChronBufSwitchGroupChronInverted = { fg = 'magenta', bg = 'fg_bright', bold = true },
  TrailBlazerTrailMarkGlobalChronBufSwitchGroupLineSortedInverted = { fg = 'cyan', bg = 'bg', bold = true },
  TrailBlazerTrailMarkBufferLocalChronInverted = { fg = 'magenta', bg = 'fg_bright', bold = true },
  TrailBlazerTrailMarkBufferLocalLineSortedInverted = { fg = 'green', bg = 'bg', bold = true },
}
