return {
  LazyButton = { fg = 'fg', bg = 'surface' },
  LazyButtonActive = { fg = 'fg_bright', bg = 'muted', bold = true },
  LazyComment = { fg = 'gray', italic = true },
  LazyCommit = { fg = 'cyan' },
  LazyCommitIssue = { fg = 'yellow' },
  LazyCommitScope = { fg = 'blue' },
  LazyCommitType = { fg = 'magenta' },
  LazyDimmed = { fg = 'muted' },
  LazyDir = { fg = 'blue' },
  LazyH1 = { fg = 'bg', bg = 'green', bold = true },
  LazyH2 = { fg = 'green', bold = true },
  LazyLocal = { fg = 'orange' },
  LazyNoCond = { fg = 'red' },
  LazyNormal = { link = 'NormalFloat' },
  LazyProgressDone = { fg = 'green' },
  LazyProgressTodo = { fg = 'muted' },
  LazyProp = { fg = 'cyan' },
  LazyReasonCmd = { fg = 'orange' },
  LazyReasonEvent = { fg = 'yellow' },
  LazyReasonFt = { fg = 'green' },
  LazyReasonImport = { fg = 'magenta' },
  LazyReasonKeys = { fg = 'blue' },
  LazyReasonPlugin = { fg = 'cyan' },
  LazyReasonRequire = { fg = 'magenta' },
  LazySpecial = { fg = 'magenta' },
  LazyTaskError = { fg = 'red' },
  LazyTaskOutput = { fg = 'fg' },
  LazyUrl = { fg = 'blue', underline = true },
  LazyValue = { fg = 'yellow' },

  MiniIconsAzure = { fg = 'blue' },
  MiniIconsBlue = { fg = 'blue' },
  MiniIconsCyan = { fg = 'cyan' },
  MiniIconsGreen = { fg = 'green' },
  MiniIconsGrey = { fg = 'gray' },
  MiniIconsOrange = { fg = 'orange' },
  MiniIconsPurple = { fg = 'magenta' },
  MiniIconsRed = { fg = 'red' },
  MiniIconsYellow = { fg = 'yellow' },

  OilDir = { fg = 'blue', bold = true },
  OilDirIcon = { fg = 'blue' },
  OilFile = { fg = 'fg' },
  OilLink = { fg = 'magenta', underline = true },
  OilLinkTarget = { fg = 'blue' },
  OilCopy = { fg = 'cyan' },
  OilCreate = { fg = 'green' },
  OilChange = { fg = 'yellow' },
  OilMove = { fg = 'orange' },
  OilDelete = { fg = 'red' },
  OilPermissionRead = { fg = 'green' },
  OilPermissionWrite = { fg = 'yellow' },
  OilPermissionExecute = { fg = 'red' },
  OilTypeDir = { fg = 'blue' },
  OilTypeFile = { fg = 'fg' },
  OilTypeLink = { fg = 'magenta' },

  CinderGroveMinimapCursor = { fg = 'fg_bright', bg = 'surface' },
  CinderGroveMinimapRange = { fg = 'orange', bg = 'bg' },
  MinimapCursor = { link = 'CinderGroveMinimapCursor' },
  MinimapRange = { link = 'CinderGroveMinimapRange' },
}
