return {
  LazyButton = { fg = 'text', bg = 'surface' },
  LazyButtonActive = { fg = 'text_bright', bg = 'overlay', bold = true },
  LazyComment = { fg = 'text_subtle', italic = true },
  LazyCommit = { fg = 'cyan' },
  LazyCommitIssue = { fg = 'warning' },
  LazyCommitScope = { fg = 'info' },
  LazyCommitType = { fg = 'purple' },
  LazyDimmed = { fg = 'text_muted' },
  LazyDir = { fg = 'info' },
  LazyH1 = { fg = 'background', bg = 'primary', bold = true },
  LazyH2 = { fg = 'primary', bold = true },
  LazyLocal = { fg = 'secondary' },
  LazyNoCond = { fg = 'error' },
  LazyNormal = { link = 'NormalFloat' },
  LazyProgressDone = { fg = 'success' },
  LazyProgressTodo = { fg = 'text_muted' },
  LazyProp = { fg = 'cyan' },
  LazyReasonCmd = { fg = 'secondary' },
  LazyReasonEvent = { fg = 'warning' },
  LazyReasonFt = { fg = 'primary' },
  LazyReasonImport = { fg = 'purple' },
  LazyReasonKeys = { fg = 'info' },
  LazyReasonPlugin = { fg = 'cyan' },
  LazyReasonRequire = { fg = 'purple' },
  LazySpecial = { fg = 'purple' },
  LazyTaskError = { fg = 'error' },
  LazyTaskOutput = { fg = 'text' },
  LazyUrl = { fg = 'info', underline = true },
  LazyValue = { fg = 'warning' },

  MiniIconsAzure = { fg = 'info' },
  MiniIconsBlue = { fg = 'info' },
  MiniIconsCyan = { fg = 'cyan' },
  MiniIconsGreen = { fg = 'success' },
  MiniIconsGrey = { fg = 'text_subtle' },
  MiniIconsOrange = { fg = 'secondary' },
  MiniIconsPurple = { fg = 'purple' },
  MiniIconsRed = { fg = 'error' },
  MiniIconsYellow = { fg = 'warning' },

  OilDir = { fg = 'info', bold = true },
  OilDirIcon = { fg = 'info' },
  OilFile = { fg = 'text' },
  OilLink = { fg = 'purple', underline = true },
  OilLinkTarget = { fg = 'info' },
  OilCopy = { fg = 'cyan' },
  OilCreate = { fg = 'success' },
  OilChange = { fg = 'warning' },
  OilMove = { fg = 'secondary' },
  OilDelete = { fg = 'error' },
  OilPermissionRead = { fg = 'success' },
  OilPermissionWrite = { fg = 'warning' },
  OilPermissionExecute = { fg = 'error' },
  OilTypeDir = { fg = 'info' },
  OilTypeFile = { fg = 'text' },
  OilTypeLink = { fg = 'purple' },

  CinderGroveMinimapCursor = { fg = 'text_bright', bg = 'surface' },
  CinderGroveMinimapRange = { fg = 'secondary', bg = 'background' },
  MinimapCursor = { link = 'CinderGroveMinimapCursor' },
  MinimapRange = { link = 'CinderGroveMinimapRange' },
}
