return {
  ObsidianRefText = { fg = 'green', underline = true },
  ObsidianRef = { fg = 'blue' },
  ObsidianBullet = { fg = 'orange' },
  ObsidianDone = { fg = 'green' },
  ObsidianTodo = { fg = 'yellow' },
  ObsidianTag = { fg = 'blue' },
  obsidiantag = { link = 'ObsidianTag' },

  OrgBulletsDash = { link = '@markup.list' },
  OrgBulletsPlus = { link = '@markup.list' },
  OrgBulletsStar = { link = '@markup.list' },

  RenderMarkdownH1 = { fg = 'green', bold = true },
  RenderMarkdownH2 = { fg = 'green', bold = true },
  RenderMarkdownH3 = { fg = 'green', bold = true },
  RenderMarkdownH4 = { fg = 'green', bold = true },
  RenderMarkdownH5 = { fg = 'green', bold = true },
  RenderMarkdownH6 = { fg = 'green', bold = true },
  RenderMarkdownH1Bg = { fg = 'green', bg = 'surface', bold = true },
  RenderMarkdownH2Bg = { fg = 'green', bg = 'surface', bold = true },
  RenderMarkdownH3Bg = { fg = 'green', bg = 'surface', bold = true },
  RenderMarkdownH4Bg = { fg = 'green', bg = 'surface', bold = true },
  RenderMarkdownH5Bg = { fg = 'green', bg = 'surface', bold = true },
  RenderMarkdownH6Bg = { fg = 'green', bg = 'surface', bold = true },
  RenderMarkdownBullet = { fg = 'orange' },
  RenderMarkdownChecked = { fg = 'green' },
  RenderMarkdownUnchecked = { fg = 'gray' },
  RenderMarkdownCode = { fg = 'fg_bright', bg = 'bg_alt' },
  RenderMarkdownCodeInline = { fg = 'fg_bright', bg = 'bg_alt' },
  RenderMarkdownQuote = { fg = 'yellow' },
  RenderMarkdownMath = { fg = 'blue' },
  RenderMarkdownLink = { fg = 'green', underline = true },
  RenderMarkdownWikiLink = { fg = 'blue', underline = true },
  RenderMarkdownTodo = { fg = 'yellow' },
  RenderMarkdownTableHead = { fg = 'fg_bright', bold = true },
  RenderMarkdownTableRow = { fg = 'fg' },
  RenderMarkdownTableFill = { fg = 'muted' },
  RenderMarkdownTableBorder = { fg = 'muted' },
}
