return {
  ObsidianRefText = { fg = 'primary', underline = true },
  ObsidianRef = { fg = 'info' },
  ObsidianBullet = { fg = 'secondary' },
  ObsidianDone = { fg = 'success' },
  ObsidianTodo = { fg = 'warning' },
  ObsidianTag = { fg = 'info' },
  obsidiantag = { link = 'ObsidianTag' },

  OrgBulletsDash = { link = '@markup.list' },
  OrgBulletsPlus = { link = '@markup.list' },
  OrgBulletsStar = { link = '@markup.list' },

  RenderMarkdownH1 = { fg = 'primary', bold = true },
  RenderMarkdownH2 = { fg = 'primary', bold = true },
  RenderMarkdownH3 = { fg = 'primary', bold = true },
  RenderMarkdownH4 = { fg = 'primary', bold = true },
  RenderMarkdownH5 = { fg = 'primary', bold = true },
  RenderMarkdownH6 = { fg = 'primary', bold = true },
  RenderMarkdownH1Bg = { fg = 'primary', bg = 'surface', bold = true },
  RenderMarkdownH2Bg = { fg = 'primary', bg = 'surface', bold = true },
  RenderMarkdownH3Bg = { fg = 'primary', bg = 'surface', bold = true },
  RenderMarkdownH4Bg = { fg = 'primary', bg = 'surface', bold = true },
  RenderMarkdownH5Bg = { fg = 'primary', bg = 'surface', bold = true },
  RenderMarkdownH6Bg = { fg = 'primary', bg = 'surface', bold = true },
  RenderMarkdownBullet = { fg = 'secondary' },
  RenderMarkdownChecked = { fg = 'success' },
  RenderMarkdownUnchecked = { fg = 'text_subtle' },
  RenderMarkdownCode = { fg = 'text_bright', bg = 'container' },
  RenderMarkdownCodeInline = { fg = 'text_bright', bg = 'container' },
  RenderMarkdownQuote = { fg = 'warning' },
  RenderMarkdownMath = { fg = 'info' },
  RenderMarkdownLink = { fg = 'primary', underline = true },
  RenderMarkdownWikiLink = { fg = 'info', underline = true },
  RenderMarkdownTodo = { fg = 'warning' },
  RenderMarkdownTableHead = { fg = 'text_bright', bold = true },
  RenderMarkdownTableRow = { fg = 'text' },
  RenderMarkdownTableFill = { fg = 'text_muted' },
  RenderMarkdownTableBorder = { fg = 'text_muted' },
}
